---
- name: Deploy docker projects
  hosts: docker
  become: true
  tasks:
    - name: Deploy compose projects
      ansible.builtin.include_role:
        name: docker_project_create
      loop: "{{ docker_projects | default([], true) }}"
      loop_control:
        loop_var: project_item
      vars:
        docker_project_create_name: "{{ project_item.name }}"
        docker_project_create_container_subdir: "{{ project_item.containers_subdirs }}"
        docker_project_create_extra_dirs: "{{ project_item.additional_dirs }}"
        docker_project_create_compose_file: "docker_projects/{{ inventory_hostname }}/{{ project_item.name }}.yml"
    - name: Remove orphan projects
      ansible.builtin.include_role:
        name: docker_project_orphan
...
