---
- name: Install docker
  hosts: docker
  become: true
  tasks:
    - name: Install docker
      ansible.builtin.include_role:
        name: docker_install

- name: Provision docker & swarm environment
  hosts: docker
  become: true
  tasks:
    - name: Bootstrap docker env
      ansible.builtin.include_role:
        name: docker_swarm_bootstrap

- name: Install dependencies
  hosts: jellyfin
  become: true
  tasks:
    - name: Install dependencies for jellyfin server
      ansible.builtin.apt:
        name:
          - intel-media-va-driver-non-free
          - firmware-misc-nonfree
          - intel-gpu-tools
        state: present
        update_cache: true
        cache_valid_time: 3600
      register: intel_firmware_install
    - name: Reboot post dependency install
      ansible.builtin.reboot:
      when: intel_firmware_install is changed # noqa: no-handler
...
